export const data = [
    {
        "id": 1,
        "type": "berries",
        "image": "../images/berries/Арбуз Русский размер F1.jpeg",
        "Name_Plant": "Земляника",
        "Ripening_season_Plant": "Июнь-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Ароматные ягоды с ананасовым вкусом",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 2,
        "type": "berries",
        "image": "../images/berries/Арбуз Русский размер F1.jpeg",
        "Name_Plant": "Арбуз",
        "Ripening_season_Plant": "Июнь-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Русский размер F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 3,
        "type": "berries",
        "image": "../images/berries/Арбуз Русский размер F1.jpeg",
        "Name_Plant": "Арбуз",
        "Ripening_season_Plant": "Июнь-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Русский размер F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 4,
        "type": "berries",
        "image": "../images/berries/Арбуз Русский размер F1.jpeg",
        "Name_Plant": "Арбуз",
        "Ripening_season_Plant": "Июнь-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Оранжевый медок",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 5,
        "type": "berries",
        "Name_Plant": "Арбуз",
        "Ripening_season_Plant": "Июнь-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Оранжевый медок F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 6,
        "type": "berries",
        "Name_Plant": "Арбуз",
        "Ripening_season_Plant": "Май-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Эльф Уафи F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 7,
        "type": "berries",
        "Name_Plant": "Малина",
        "Ripening_season_Plant": "Май-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Медовая",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 8,
        "type": "berries",
        "Name_Plant": "Земляника",
        "Ripening_season_Plant": "Май-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Лесная",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 9,
        "type": "berries",
        "Name_Plant": "Клюква",
        "Ripening_season_Plant": "Май-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Бен Лир",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 10,
        "type": "berries",
        "Name_Plant": "Клюква",
        "Ripening_season_Plant": "Май-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Бен Лир",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 11,
        "type": "berries",
        "Name_Plant": "Арбуз",
        "Ripening_season_Plant": "Май-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Икар",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 12,
        "type": "berries",
        "Name_Plant": "Земляника",
        "Ripening_season_Plant": "Май-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Золотая полянка",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 13,
        "type": "berries",
        "Name_Plant": "Арбуз",
        "Ripening_season_Plant": "Май-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Лимончино",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 14,
        "type": "berries",
        "Name_Plant": "Земляника",
        "Ripening_season_Plant": "Май-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Ремонтантная C-141 F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 15,
        "type": "berries",
        "Name_Plant": "Земляника",
        "Ripening_season_Plant": "Май-Июль",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Ремонтантная C-141 F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 16,
        "type": "berries",
        "Name_Plant": "Земляника",
        "Ripening_season_Plant": "Май-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Московский деликатес F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 17,
        "type": "berries",
        "Name_Plant": "Земляника",
        "Ripening_season_Plant": "Июнь-Июль",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Заря F1 Элит мини",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 18,
        "type": "berries",
        "Name_Plant": "Земляника",
        "Ripening_season_Plant": "Июнь-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Белоснежка",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 19,
        "type": "berries",
        "Name_Plant": "Малина",
        "Ripening_season_Plant": "Июнь-Июль",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Жёлтая ягодка",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 20,
        "type": "berries",
        "Name_Plant": "Голубика",
        "Ripening_season_Plant": "Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Голубая россыпь",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 21,
        "type": "berries",
        "Name_Plant": "Черника",
        "Ripening_season_Plant": "Июль",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Черника обыкновенная Тёмная ночь",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 22,
        "type": "berries",
        "Name_Plant": "Черника",
        "Ripening_season_Plant": "Июль",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Черника обыкновенная Тёмная ночь",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 23,
        "type": "berries",
        "Name_Plant": "Земляника",
        "Ripening_season_Plant": "Июнь-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Земляника Вкуснятина F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 24,
        "type": "berries",
        "Name_Plant": "Земляника",
        "Ripening_season_Plant": "Июнь-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Земляника Вкуснятина F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 25,
        "type": "berries",
        "Name_Plant": "Арбуз",
        "Ripening_season_Plant": "Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Шуга Бейби",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 26,
        "type": "berries",
        "Name_Plant": "Голубика",
        "Ripening_season_Plant": "Июнь-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Голубика высокорослая Лесное сокровище",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 27,
        "type": "berries",
        "Name_Plant": "Арбуз",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Арбуз Голден Леди F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 28,
        "type": "berries",
        "Name_Plant": "Малина",
        "Ripening_season_Plant": "Июнь-Июль",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Малина красная Рубин",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 29,
        "type": "berries",
        "Name_Plant": "Черника",
        "Ripening_season_Plant": "Июль-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Черника Заздравная",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 30,
        "type": "berries",
        "Name_Plant": "Ежевика",
        "Ripening_season_Plant": "Июнь-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Ежевика Агавам",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 31,
        "type": "berries",
        "Name_Plant": "Брусника",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Брусника Рубин",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 32,
        "type": "berries",
        "Name_Plant": "Клубника",
        "Ripening_season_Plant": "Июнь-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Клубника Флориан F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 33,
        "type": "berries",
        "Name_Plant": "Черника",
        "Ripening_season_Plant": "Июль-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Лесная жемчужина",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 34,
        "type": "berries",
        "Name_Plant": "Малина",
        "Ripening_season_Plant": "Июнь-Июль",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Сладкая ягодка",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 35,
        "type": "berries",
        "Name_Plant": "Ежевика",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Ежевика Чародейка",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 36,
        "type": "berries",
        "Name_Plant": "Арбуз",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Арбуз Оранжевый медок F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 37,
        "type": "berries",
        "Name_Plant": "Клюква",
        "Ripening_season_Plant": "Июль-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Клюква крупноплодная Королева сада",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 38,
        "type": "berries",
        "Name_Plant": "Черника",
        "Ripening_season_Plant": "Июль",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Лесная целительница",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 39,
        "type": "berries",
        "Name_Plant": "Клубника",
        "Ripening_season_Plant": "Июнь-Октябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Всемирный деликатес, Смесь F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 40,
        "type": "vegetables",
        "Name_Plant": "Огурец",
        "Ripening_season_Plant": "Июнь-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Огурец Корюшка F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 41,
        "type": "vegetables",
        "Name_Plant": "Томат",
        "Ripening_season_Plant": "Июль-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Томат Джек Пот F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 42,
        "type": "vegetables",
        "Name_Plant": "Морковь",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Морковь Пурпл Дракон",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 43,
        "type": "vegetables",
        "Name_Plant": "Капуста",
        "Ripening_season_Plant": "Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Капуста белокочанная Королева засолки F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 44,
        "type": "vegetables",
        "Name_Plant": "Баклажан",
        "Ripening_season_Plant": "Июль-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Санчо Панса",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 45,
        "type": "vegetables",
        "Name_Plant": "Баклажан",
        "Ripening_season_Plant": "Июль-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Ультраранний F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 46,
        "type": "vegetables",
        "Name_Plant": "Баклажан",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Десерт Голиафа",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 47,
        "type": "vegetables",
        "Name_Plant": "Баклажан",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Мраморный Восторг",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 48,
        "type": "vegetables",
        "Name_Plant": "Баклажан",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Виолетта ди Фиренце",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 49,
        "type": "vegetables",
        "Name_Plant": "Баклажан",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Генеральский",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 50,
        "type": "vegetables",
        "Name_Plant": "Баклажан",
        "Ripening_season_Plant": "Июль-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Алёшка F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 51,
        "type": "vegetables",
        "Name_Plant": "Бобы",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Вировские сахарные",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 52,
        "type": "vegetables",
        "Name_Plant": "Бобы",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Чёрные алмазы",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 53,
        "type": "vegetables",
        "Name_Plant": "Бобы",
        "Ripening_season_Plant": "Июль-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Царский урожай",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 54,
        "type": "vegetables",
        "Name_Plant": "Бобы",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Дачник",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 55,
        "type": "vegetables",
        "Name_Plant": "Чечевица",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Коричневая",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 56,
        "type": "vegetables",
        "Name_Plant": "Горох",
        "Ripening_season_Plant": "Июнь-Июль",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Голден Свит",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 57,
        "type": "vegetables",
        "Name_Plant": "Горох",
        "Ripening_season_Plant": "Июнь-Июль",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Вкусный стручок",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 58,
        "type": "vegetables",
        "Name_Plant": "Горох",
        "Ripening_season_Plant": "Июнь-Июль",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Самый ранний F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 59,
        "type": "vegetables",
        "Name_Plant": "Горох",
        "Ripening_season_Plant": "Июнь-Июль",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Овощной Хаф Пинт",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 60,
        "type": "vegetables",
        "Name_Plant": "Дыня",
        "Ripening_season_Plant": "Июль-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Торпеда Сибирико",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 61,
        "type": "vegetables",
        "Name_Plant": "Дыня",
        "Ripening_season_Plant": "Июль-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Чудо-Юдо",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 62,
        "type": "vegetables",
        "Name_Plant": "Дыня",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Люкс-87",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 63,
        "type": "vegetables",
        "Name_Plant": "Дыня",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Майорка F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 64,
        "type": "vegetables",
        "Name_Plant": "Кабачок",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Внучок",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 65,
        "type": "vegetables",
        "Name_Plant": "Кабачок",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Страусенок",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 66,
        "type": "vegetables",
        "Name_Plant": "Кабачок",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Цуккини Осьминог",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 67,
        "type": "vegetables",
        "Name_Plant": "Кабачок",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Бананы на Грядке F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 68,
        "type": "vegetables",
        "Name_Plant": "Капуста",
        "Ripening_season_Plant": "Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Белокочанная Королева засолки F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 69,
        "type": "vegetables",
        "Name_Plant": "Капуста",
        "Ripening_season_Plant": "Июнь-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Цветная Снежная Баба F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 70,
        "type": "vegetables",
        "Name_Plant": "Капуста",
        "Ripening_season_Plant": "Июнь-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Пекинская Натсуки F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 71,
        "type": "vegetables",
        "Name_Plant": "Капуста",
        "Ripening_season_Plant": "Сентябрь-Октябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Белокочанная Альбатрос F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 72,
        "type": "vegetables",
        "Name_Plant": "Картофель",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Сказка",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 73,
        "type": "vegetables",
        "Name_Plant": "Картофель",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Колобок",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 74,
        "type": "vegetables",
        "Name_Plant": "Картофель",
        "Ripening_season_Plant": "Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Фермер",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 75,
        "type": "vegetables",
        "Name_Plant": "Картофель",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Панда",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 76,
        "type": "vegetables",
        "Name_Plant": "Кукуруза",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Сахарная Спирит F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 77,
        "type": "vegetables",
        "Name_Plant": "Кукуруза",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Свит Сириус F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 78,
        "type": "vegetables",
        "Name_Plant": "Кукуруза",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Оватонна F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 79,
        "type": "vegetables",
        "Name_Plant": "Лук",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Репчатый многозачатковый Семейный хоровод",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 80,
        "type": "vegetables",
        "Name_Plant": "Лук",
        "Ripening_season_Plant": "Август-Октябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Репчатый Ялтинский Красный",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 81,
        "type": "vegetables",
        "Name_Plant": "Лук",
        "Ripening_season_Plant": "Июль",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Шалот (семейный) Монастырский",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 82,
        "type": "vegetables",
        "Name_Plant": "Лук",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Репчатый Зебрун многозачатковый",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 83,
        "type": "vegetables",
        "Name_Plant": "Морковь",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Пурпл Дракон",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 84,
        "type": "vegetables",
        "Name_Plant": "Морковь",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Нантская 5 Суперсочная",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 85,
        "type": "vegetables",
        "Name_Plant": "Морковь",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Красный зайка",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 86,
        "type": "vegetables",
        "Name_Plant": "Морковь",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Столовая Чурчхела Желтая",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 87,
        "type": "vegetables",
        "Name_Plant": "Огурец",
        "Ripening_season_Plant": "Июнь-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Корюшка F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 88,
        "type": "vegetables",
        "Name_Plant": "Огурец",
        "Ripening_season_Plant": "Июнь-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Капитан Засолкин F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 89,
        "type": "vegetables",
        "Name_Plant": "Огурец",
        "Ripening_season_Plant": "Июнь-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Хрустяшка F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 90,
        "type": "vegetables",
        "Name_Plant": "Перец сладкий",
        "Ripening_season_Plant": "Июль-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Забор Желтый F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 91,
        "type": "vegetables",
        "Name_Plant": "Перец сладкий",
        "Ripening_season_Plant": "Июль-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Забор Красный F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 92,
        "type": "vegetables",
        "Name_Plant": "Перец сладкий",
        "Ripening_season_Plant": "Июль-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Ламуйо F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 93,
        "type": "vegetables",
        "Name_Plant": "Перец сладкий",
        "Ripening_season_Plant": "Июль-Август",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Синдерела F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 94,
        "type": "vegetables",
        "Name_Plant": "Редис",
        "Ripening_season_Plant": "Май-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Французский Поцелуй",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 95,
        "type": "vegetables",
        "Name_Plant": "Редис",
        "Ripening_season_Plant": "Май-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Фелиция",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 96,
        "type": "vegetables",
        "Name_Plant": "Редис",
        "Ripening_season_Plant": "Май-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Сибирский Гигант",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 97,
        "type": "vegetables",
        "Name_Plant": "Редис",
        "Ripening_season_Plant": "Май-Октябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Экспресс 16 F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 98,
        "type": "vegetables",
        "Name_Plant": "Свекла",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Пабло F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 99,
        "type": "vegetables",
        "Name_Plant": "Свекла",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Кестрел F1",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 100,
        "type": "vegetables",
        "Name_Plant": "Свекла",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Бордо 237",
        "Status_Plant": "Семена не посажены",
    },
    {
        "id": 101,
        "type": "vegetables",
        "Name_Plant": "Свекла",
        "Ripening_season_Plant": "Август-Сентябрь",
        "Purpose_Plant": "Сад и огород",
        "Discribe_Plant": "Столовая Щец-борщец",
        "Status_Plant": "Семена не посажены",
    },

]